language: python

matrix:
  include:
  - name: "2.7 Unit Test"
    python: "2.7"
  - name: "3.5 Unit Test"
    python: "3.5"
  - name: "3.6 Unit Test"
    python: "3.6"

install:
  - printenv | sort
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy nose
  - source activate test-environment
  - conda install -c openbabel openbabel python=$TRAVIS_PYTHON_VERSION
  - conda install -c rdkit rdkit python=$TRAVIS_PYTHON_VERSION
  - conda clean --packages --tarballs
  - conda list
script: make test
